#!/bin/sh

# After running this script the machine should be rebooted to enable updates and permissions changes to take effect.

# Update system
apt-get update && apt-get dist-upgrade -y

# Install and enable docker
apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io
systemctl enable docker

# Add current user to docker group so sudo not needed
usermod -aG docker $USER

# Install docker-compose
latest_version=$(git ls-remote --tags https://github.com/docker/compose.git | awk '{print $2}' | grep -Ev '{}|rc|docs' | awk -F"/" '{print $3}' | sort -t '/' -V | tail -n 1)
curl -L "https://github.com/docker/compose/releases/download/$latest_version/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose